feat: send_destination method added.
smartcar/python-sdk pull request #129
Opened 2023-12-04 23:38 UTC by aytekin-smartcar

## Summary
`send_destination` method added. This is a core endpoint.

2023-12-05 18:34 UTC, nbry requested changes
Requesting a few minor updates to the documentation.

2023-12-05 18:34 UTC, nbry commented on REFERENCE.md
> +#### Return
We need an Arguments table to show the parameters - latitude (Float), longitude (Float)

2023-12-05 18:34 UTC, nbry commented on REFERENCE.md
> +### `send_destination(self)`
We have to add the latitude, longitude params to the function signature.

i.e.
```
### `send_destination(self, latitude, longitude)`
```

2023-12-13 21:51 UTC, bharathGuna approved these changes

2023-12-14 17:50 UTC, nbry approved these changes

2023-12-15 18:14 UTC, merged