fix: battery capacity parsing bad header
smartcar/python-sdk pull request #90
Opened 2021-02-12 19:52 UTC by rsimari

Asana: https://app.asana.com/0/1158554234878597/1199929686492380/f

2021-02-12 21:57 UTC, bharathGuna approved these changes

2021-02-15 20:57 UTC, gurpreetatwal requested changes

2021-02-15 20:57 UTC, gurpreetatwal commented on smartcar/vehicle.py
> -            "unit_system": response.headers["sc-unit-system"],
Can you update the documentation in the readme as well

2021-02-15 21:52 UTC, gurpreetatwal approved these changes

2021-02-15 22:00 UTC, merged