Smartcar exception v2
smartcar/python-sdk pull request #92
Opened 2021-03-15 19:45 UTC by rsimari

Asana: https://app.asana.com/0/1199874972215393/1200046735503443/f

2021-03-16 16:09 UTC, rsimari commented on smartcar/exceptions.py
> +                self.type = json["type"]
Im making the assumption that if `type` exists then so do all the other fields.  If there's no `resolution` or `detail` then are we sending back empty values or just not including the properties on the errors?

2021-03-16 17:18 UTC, rsimari commented
adding docs...

2021-03-17 16:14 UTC, rsimari commented on smartcar/exceptions.py
> +                self.type = json["type"]
For now the team decided to send back `null` instead of not including the attribute in the response

2021-03-24 14:33 UTC, rsimari commented on smartcar/requester.py
> +        if isinstance(e, E.SmartcarException) or isinstance(e, E.SmartcarExceptionV2):
If we do what we did in Java, SmartcarExceptionV2 should inherit from SmartcarException and then we only have to do one instance check (same with our clients)

2021-04-01 05:08 UTC, gurpreetatwal requested changes

2021-04-01 05:08 UTC, gurpreetatwal commented on smartcar/requester.py
> +        elif "v2.0" in url:
```suggestion
        elif "/v2.0/" in url:
```

2021-04-01 05:08 UTC, gurpreetatwal commented on smartcar/requester.py
> +from . import api, smartcar
unused?

2021-04-01 05:08 UTC, gurpreetatwal commented on tests/test_smartcar.py
> +            self.assertTrue(err.type == "TYPE")
should also add a test that checks the stringification

2021-04-01 05:08 UTC, gurpreetatwal commented on tests/test_smartcar.py
> +    def test_v2_exception(self):
can we also add a test for the string response case

2021-04-06 21:47 UTC, gurpreetatwal approved these changes
There are some print statements that need to be removed, but otherwise LGTM

2021-04-06 21:52 UTC, gurpreetatwal requested changes

2021-04-06 21:52 UTC, gurpreetatwal commented on README.md
> +- For more detailed errors, use the `v2.0` api by using `smartcar.set_api_version("2.0")`. All exceptions will be of type `smartcar.SmartcarExceptionV2`
Two notes here:
1. Can we document the properties of `SmartcarExceptionV2` 
2. Should we have  `v1.0` and `v2.0`  subsections for the `Handing Exceptions` heading?

2021-04-06 21:52 UTC, gurpreetatwal commented on README.md
> +
Need to document the `set_api_version` method

2021-04-08 22:55 UTC, gurpreetatwal approved these changes

2021-04-24 00:22 UTC, merged